export type SharedPageProps = {
    auth: {
        user: {
            id: string;
            name: string;
            email: string;
            emailVerified: boolean;
        } | null;
        tenant: {
            provisioningStatus: 'pending' | 'provisioning' | 'ready' | 'failed';
            available: boolean;
        } | null;
    };
    flash: {
        status: string | null;
        error: string | null;
    };
    localization: {
        locale: string;
        languages: Array<{
            code: string;
            nativeName: string;
        }>;
        translations: UiTranslations;
    };
};

export type UiTranslations = {
    common: {
        email: string;
        password: string;
        backToLogin: string;
        accountRecovery: string;
        preparingRequest: string;
    };
    authLayout: {
        homeLabel: string;
        brandKicker: string;
        brandCopy: string;
        trustNote: string;
        selectLanguage: string;
    };
    appLayout: {
        dashboardLabel: string;
        navigationLabel: string;
        overview: string;
        organization: string;
        tenantManagement: string;
        tenantUsers: string;
        organizationUnitTypes: string;
        organizationalUnits: string;
        collapseSidebar: string;
        expandSidebar: string;
        logout: string;
    };
    login: {
        headTitle: string;
        eyebrow: string;
        title: string;
        description: string;
        forgotPassword: string;
        submit: string;
        processing: string;
        noAccount: string;
        register: string;
    };
    register: {
        headTitle: string;
        eyebrow: string;
        title: string;
        description: string;
        name: string;
        passwordConfirmation: string;
        note: string;
        submit: string;
        processing: string;
        hasAccount: string;
        login: string;
    };
    forgotPassword: {
        headTitle: string;
        title: string;
        description: string;
        status: string;
        submit: string;
        rememberedPassword: string;
    };
    resetPassword: {
        headTitle: string;
        title: string;
        description: string;
        newPassword: string;
        passwordHint: string;
        passwordConfirmation: string;
        invalidLink: string;
        submit: string;
        processing: string;
    };
    verifyEmail: {
        headTitle: string;
        eyebrow: string;
        title: string;
        emailFallback: string;
        description: string;
        submit: string;
        note: string;
        otherAccount: string;
        logout: string;
    };
    dashboard: {
        headTitle: string;
        eyebrow: string;
        title: string;
        description: string;
        accountStatus: string;
        emailVerified: string;
        verifiedDescription: string;
        nextStep: string;
        organizationSetup: string;
        organizationDescription: string;
        manageOrganization: string;
    };
    organization: {
        headTitle: string;
        backToDashboard: string;
        eyebrow: string;
        title: string;
        description: string;
        existingLabel: string;
        newLabel: string;
        formTitle: string;
        name: string;
        taxNumber: string;
        taxNumberHint: string;
        createSubmit: string;
        creating: string;
        updateSubmit: string;
        updating: string;
        created: string;
        updated: string;
        netZeroTitle: string;
        netZeroDescription: string;
        netZeroRequestSubmit: string;
        netZeroRequesting: string;
        netZeroRequested: string;
        netZeroStatusLabel: string;
        netZeroStatuses: {
            pending: string;
            provisioning: string;
            ready: string;
            failed: string;
        };
    };
    tenantUsers: {
        headTitle: string;
        eyebrow: string;
        title: string;
        description: string;
        add: string;
        searchPlaceholder: string;
        allStatuses: string;
        activeOnly: string;
        inactiveOnly: string;
        filter: string;
        clearFilters: string;
        name: string;
        email: string;
        active: string;
        createdAt: string;
        actions: string;
        activeLabel: string;
        inactiveLabel: string;
        empty: string;
        results: string;
        previous: string;
        next: string;
        createTitle: string;
        editTitle: string;
        password: string;
        passwordConfirmation: string;
        passwordHint: string;
        cancel: string;
        createSubmit: string;
        updateSubmit: string;
        processing: string;
        edit: string;
        delete: string;
        deleteTitle: string;
        deleteConfirmation: string;
        deleteSubmit: string;
        created: string;
        updated: string;
        deleted: string;
    };
    tenantOrganizationalUnits: {
        headTitle: string;
        eyebrow: string;
        title: string;
        description: string;
        add: string;
        treeTitle: string;
        detailsTitle: string;
        selectHint: string;
        empty: string;
        root: string;
        name: string;
        parent: string;
        type: string;
        noType: string;
        inactiveType: string;
        structuralRole: string;
        standard: string;
        company: string;
        facility: string;
        sortOrder: string;
        cancel: string;
        createTitle: string;
        editTitle: string;
        createSubmit: string;
        updateSubmit: string;
        processing: string;
        edit: string;
        created: string;
        updated: string;
        classificationConflict: string;
        parentCycle: string;
    };
    tenantOrganizationUnitTypes: {
        headTitle: string;
        eyebrow: string;
        title: string;
        description: string;
        add: string;
        name: string;
        listName: string;
        status: string;
        activeLabel: string;
        inactiveLabel: string;
        sortOrder: string;
        unitsCount: string;
        actions: string;
        empty: string;
        createTitle: string;
        editTitle: string;
        cancel: string;
        createSubmit: string;
        updateSubmit: string;
        processing: string;
        edit: string;
        delete: string;
        deleteTitle: string;
        deleteConfirmation: string;
        deleteSubmit: string;
        deleteDisabled: string;
        created: string;
        updated: string;
        deleted: string;
        inUse: string;
    };
};
